### ISSUE TITLE
Modal 컴포넌트 구현

### ISSUE THREAD

**Issue by zoonyoung** [sprint-military-9team/sprint_4_thejulge#17]
## 📌 요약
Modal Portal을 활용한 Modal Component구현

## 📌 ToDo
- [ ] Modal 컴포넌트 스타일 구현
- [ ] 외부 클릭시 Modal 화면이 종료되는 hooks 구현
- [ ] 외부 스크롤 방지하는 함수 구현
