### ISSUE TITLE
공고 상세(사장) 페이지 구현

### ISSUE THREAD

**Issue by armd482** [sprint-military-9team/sprint_4_thejulge#27]
## 📌 요약
사장 공고 상세 페이지 구현 

## 📌 ToDo
- UI구현
- [x] 공고 정보 컴포넌트 제작
- [x] 신청자 목록 컴포넌트 제작 
- [x] 공고 정보 컴포넌트 반응형 구현(마지막)
- [x] 신청자 목록 컴포넌트 반응형 구현(마지막)

- 기능 구현
- [x] 공고 정보, 신청자 목록 api 구현 및 연결
- [x] 승인하기, 거절하기 버튼 기능 구현
