### ISSUE TITLE
내 프로필 상세 페이지 구현 + 내 프로필 등록UI

### ISSUE THREAD

**Issue by kimtaejin3** [sprint-military-9team/sprint_4_thejulge#29]
## 📌 요약
내 프로필 상세 페이지 구현하기

## 📌 ToDo
- [x] 내 프로필 상세 UI 작업 (내 프로필 없을시)
- [x] 내 프로필 상세 UI 작업 (내 프로필 있고 신청 내역 없을때)
- [x] 내 프로필 상세 UI 작업 (내 프로필 있고 신청 내역 있을때)
- [x] 상세 페이지에서 내 프로필 등록 페이지 띄우기 
- [x] API 연동
- [ ] 회원기능 연동
