### ISSUE TITLE
헤더 컴포넌트 오류 수정

### ISSUE THREAD

**Issue by armd482** [sprint-military-9team/sprint_4_thejulge#38]
## 📌 요약
마지막 메세지 클릭 시 알림창 자동으로 닫히는 오류 수정
index 파일 추가
로고 클릭 시 메인 페이이 이동하는 코드 추가
## 📌 ToDo
- [x] 알림창 렌더링 조건문 변경
- [x] index 파일 추가
- [x] 로고 link 태그 추가
