### ISSUE TITLE
사장 공고 상세 컴포넌트 구현

### ISSUE THREAD

**Issue by armd482** [sprint-military-9team/sprint_4_thejulge#49]
## 📌 요약
구현하고자 하는 기능을 첨부하고 간단히 설명해주세요.!
사장 공고 상세 컴포넌트 구현
## 📌 ToDo
- UI
- [x] 기본 UI 제작
- [x] 미디어 쿼리 제작

- 기능
- [x] 등록하기 기능 구현
- [x] x버튼으로 닫기
