### ISSUE TITLE
Scss 기본 셋팅

### ISSUE THREAD

**Issue by zoonyoung** [sprint-military-9team/sprint_4_thejulge#7]
## 📌 요약
reset, mixins, colors, media 기본 셋팅 설정

## 📌 ToDo
- [x] _reset.scss 설정 
- [x] _common.scss 설정
- [x] _colors.scss 설정
- [x] _media.scss 설정
