### ISSUE TITLE
header, 공고 상세 페이지 api 에러 처리

### ISSUE THREAD

**Issue by armd482** [sprint-military-9team/sprint_4_thejulge#79]
## 📌 요약
구현하고자 하는 기능을 첨부하고 간단히 설명해주세요.!
header, 공고 상세 페이지 api 에러 처리
## 📌 ToDo
Header 컴포넌트
- [x] 유저 알림 조회 함수 에러 처리
- [x] 유저 알림 읽음 함수 에러 처리

-공고 추가/편집 컴포넌트
- [x] loading중인 경우 버튼 비활성화
- [x] 입력 focus out 에러 조건 추가
- [x] 공고 추가, 공고 편집 api 에러 처리

- 공고 상세페이지
- [x] 가게 데이터, 공고 데이터 불러오는 함수 에러 처리
- [x] 지원 상태 변경 함수 에러 처리
