### ISSUE TITLE
Header 컴포넌트 서버 컴포넌트로 변경

### ISSUE THREAD

**Issue by armd482** [sprint-military-9team/sprint_4_thejulge#82]
## 📌 요약
구현하고자 하는 기능을 첨부하고 간단히 설명해주세요.!

## 📌 ToDo
- [ ] search 부분  컴포넌트 분리
- [ ] 기존 header 컴포넌트 서버 컴포넌트화
- [ ] 메인 페이지 서버 컴포넌트화
