### ISSUE TITLE
가게 정보 상세페이지 ui 수정

### ISSUE THREAD

**Issue by armd482** [sprint-military-9team/sprint_4_thejulge#92]
## 📌 요약
가게 정보 상세페이지 ui 수정
## 📌 ToDo
- [x] 가게 정보 컴포넌트 수정
- [x] 가게, 공고 등록 컴포넌트 수정
- [x] 등록한 공고 내역 수정
- [x] 가게정보편집 모달 컴포넌트 수정
